from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

browser=webdriver.Chrome(executable_path="C:/go-workspace/python/driver/chromedriver")
browser.get("https://www.amazon.com/")
browser.find_element_by_id('nav-link-accountList').click()
browser.find_element_by_xpath(".//input[@type='email']").send_keys('   ')
browser.find_element_by_id("continue").click()
browser.find_element_by_id("ap_password").send_keys("   ")
browser.find_element_by_id("signInSubmit").click()
elem = browser.find_element_by_id('twotabsearchtextbox')
elem.send_keys('laptops')
elem = browser.find_element_by_class_name('nav-input')
time.sleep(2)
elem.click()
#product = browser.find_element_by_xpath('//*[@id="search"]/div[1]/div[2]/div/span[3]/div[2]/div[2]/div/span/div/div/div/div/div[2]/div[2]/div/div[1]/div/div/div[1]/h2/a/span')
#print(product.text)
#product = browser.find_elements_by_xpath('//*[@id="search"]/div[1]/div[2]/div/span[3]/div[2]/div[2]/div/span/div/div/div/div/div[2]/div[2]/div/div[1]/div/div/div[1]/h2/a/span')
#print(product[0].text)
#product = browser.find_elements_by_xpath('//*[@id="search"]/div[1]/div[2]/div/span[3]/div[2]/div[2]/div/span/div/div/div/div/div[2]/div[2]/div/div[1]/div/div/div[1]/h2/a/span')
#print(product[0].text)
product = browser.find_element_by_partial_link_text('Lenovo IdeaPad 3 14" Laptop, 14.0" FHD (1920 x 1080) Display, AMD Ryzen 5 3500U Processor, 8GB DDR4 RAM, 256GB SSD, AMD Radeon Vega 8 Graphics, Narrow Bezel, Windows 10, 81W0003QUS, Abyss Blue')
print(product.text)
product.click()
time.sleep(5)
browser.find_element_by_id("add-to-cart-button").click()
time.sleep(6)

browser.find_element_by_id("attach-close_sideSheet-link").click()
time.sleep(2)
#browser.find_element_by_id("attach-close_sideSheet-link").click()
#time.sleep(2)
elem = browser.find_element_by_id('twotabsearchtextbox')
elem.clear()
elem.send_keys("earphone")
time.sleep(5)
browser.find_element_by_class_name('nav-input').click()
time.sleep(3)
product1 = browser.find_element_by_link_text('Panasonic ErgoFit In-Ear Earbud Headphones RP-HJE120K Dynamic Crystal-Clear Sound, Ergonomic Comfort-Fit, 9mm, Black')
print(product1.text)
product1.click()
time.sleep(3)
browser.find_element_by_id("add-to-cart-button").click()
time.sleep(3)
browser.find_element_by_id("attach-close_sideSheet-link").click()
time.sleep(2)

time.sleep(5)
elem = browser.find_element_by_id('twotabsearchtextbox')
elem.clear()
#elem.send_keys("books best sellers")
#time.sleep(5)
#elem = browser.find_element_by_class_name('nav-input')
#time.sleep(2)
#elem.click()
#time.sleep(2)
#product2 = browser.find_element_by_link_text('The Room Where It Happened: A White House Memoir')
#product2.click()
#time.sleep(3)
#browser.find_element_by_id("add-to-cart-button").click()


time.sleep(5)
#elem = browser.find_element_by_id('twotabsearchtextbox')
#elem.clear()
#elem.send_keys("L'Oreal lipstick")
#time.sleep(5)
#elem = browser.find_element_by_class_name('nav-input')
#time.sleep(2)
#elem.click()
#time.sleep(2)
#product3 = browser.find_element_by_link_text("L'Oreal Paris Makeup Colour Riche Original Creamy, Hydrating Satin Lipstick, 760 Silverstone, 1 Count")
#product3.click()
#time.sleep(3)
#browser.find_element_by_id("add-to-wishlist-button-submit").click()
#time.sleep(3)
#browser.find_element_by_id("w-button-text").click()
#time.sleep(3)
#browser.find_element_by_class_name("a-button-text").click()
#time.sleep(3)
browser.find_element_by_id('nav-cart-count').click()
time.sleep(7)
browser.find_element_by_xpath('//*[@id="sc-item-C0cdc6b95-cc70-4fe4-aadd-c8b178c4fc12"]/div[4]/div/div[1]/div/div/div[2]/div[1]/span[2]/span/input').click()
time.sleep(3)
browser.find_element_by_class_name('a-button-input').click()
time.sleep(3)

